import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import "./globals.scss";

const ibm_plex_mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: "700"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body className={ibm_plex_mono.className}>
        {/* <style jsx global>{`
        html {
          font-family: ${ibm_plex_mono.style.fontFamily};
        }
      `}</style> */}
        {children}
      </body>
    </html>
  );
}
